# Generated by Django 4.2.6 on 2023-12-07 14:22

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsMessageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_id', models.CharField(default='details_id', max_length=128)),
                ('message', models.CharField(default='message', max_length=200)),
                ('user', models.CharField(default='user', max_length=200)),
                ('project', models.CharField(default='project', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'details_message_table',
            },
        ),
        migrations.CreateModel(
            name='KeyMessageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'key_message_table',
            },
        ),
        migrations.CreateModel(
            name='KeyProgramMetricTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(default='metric', max_length=200)),
                ('fv_target', models.CharField(default='fv_target', max_length=250)),
                ('current_week_actual', models.CharField(default='current_week_actual', max_length=200)),
                ('current_week_plan', models.CharField(default='current_week_plan', max_length=200)),
                ('status', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('comments', models.CharField(default='comments', max_length=250)),
                ('metric_id', models.CharField(default='metric_id', max_length=100)),
                ('project', models.CharField(default='project', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(default='user', max_length=100)),
            ],
            options={
                'db_table': 'key_program_metric_table',
            },
        ),
        migrations.CreateModel(
            name='LinksMetricTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links_url', models.CharField(default='links_url', max_length=250)),
                ('comments', models.CharField(default='comments', max_length=200)),
                ('links_id', models.CharField(default='links_id', max_length=100)),
                ('project', models.CharField(default='project', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(default='user', max_length=100)),
            ],
            options={
                'db_table': 'links_table',
            },
        ),
        migrations.CreateModel(
            name='RiskTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.CharField(default='problem_statement', max_length=250)),
                ('status', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('owner', models.CharField(default='owner', max_length=200)),
                ('message', models.CharField(default='message', max_length=250)),
                ('eta', models.DateTimeField(default=datetime.datetime(2023, 12, 7, 19, 52, 12, 165425))),
                ('risk', models.DateTimeField(default=datetime.datetime(2023, 12, 7, 19, 52, 12, 165425))),
                ('severity', django_mysql.models.ListTextField(models.CharField(max_length=10), size=100)),
                ('impact', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('risk_id', models.CharField(default='risk_id', max_length=100)),
                ('project', models.CharField(default='project', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(default='user', max_length=100)),
                ('display', models.CharField(default='false', max_length=100)),
            ],
            options={
                'db_table': 'risk_table',
            },
        ),
        migrations.CreateModel(
            name='ScheduleMetricTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(default='milestone', max_length=250)),
                ('por_commit', models.DateTimeField(default='por_commit')),
                ('por_trend', models.DateTimeField(default='por_trend')),
                ('status', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('comments', models.CharField(default='comments', max_length=200)),
                ('schedule_id', models.CharField(default='schedule_id', max_length=100)),
                ('project', models.CharField(default='project', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(default='user', max_length=100)),
            ],
            options={
                'db_table': 'schedule_table',
            },
        ),
    ]
