# Generated by Django 4.2.6 on 2023-12-15 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktable',
            name='eta',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 11, 1, 33, 805425)),
        ),
        migrations.AlterField(
            model_name='risktable',
            name='risk',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 11, 1, 33, 805425)),
        ),
    ]
