# Generated by Django 3.2.6 on 2023-10-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keymessage',
            name='message',
        ),
    ]
