# Generated by Django 3.2.6 on 2023-10-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0002_remove_keymessage_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyMessageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'key_message_table',
            },
        ),
    ]
