# Generated by Django 3.2.6 on 2023-10-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0003_keymessagetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_table',
            },
        ),
    ]
